# Generated by Django 4.1.1 on 2022-10-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="isPublished",
            field=models.BooleanField(default=False),
        ),
    ]
