# Generated by Django 4.1.1 on 2022-10-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_post_ispublished"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
